const dummy = {
  models: [
    {
      id: 1,
      mname: 'model_name',
      kw: [
        'awareness',
        'young',
        'adolescent',
        'adult',
        'prevalence',
        'cidarette',
        'person',
        'teenage',
        'future',
        'younger',
        'teen',
        'participation',
        'teenager',
        'disadvantaged',
        'schoenborn',
        'initiation',
        'ministry',
        'use',
        'gindi',
        'education'
      ],
      score: 20
    },
    {
      id: 10,
      mname: 'model_name',
      kw: [
        'awareness',
        'young',
        'adolescent',
        'adult',
        'prevalence',
        'cidarette',
        'person',
        'teenage',
        'future',
        'younger',
        'teen',
        'participation',
        'teenager',
        'disadvantaged',
        'schoenborn',
        'initiation',
        'ministry',
        'use',
        'gindi',
        'education'
      ],
      score: 20
    },
    {
      id: 2,
      mname: 'model_name',
      kw: [
        'awareness',
        'young',
        'adolescent',
        'adult',
        'prevalence',
        'cidarette',
        'person',
        'teenage',
        'future',
        'younger',
        'teen',
        'participation',
        'teenager',
        'disadvantaged',
        'schoenborn',
        'initiation',
        'ministry',
        'use',
        'gindi',
        'education'
      ],
      score: 20
    },
    {
      id: 3,
      mname: 'model_name',
      kw: [
        'awareness',
        'young',
        'adolescent',
        'adult',
        'prevalence',
        'cidarette',
        'person',
        'teenage',
        'future',
        'younger',
        'teen',
        'participation',
        'teenager',
        'disadvantaged',
        'schoenborn',
        'initiation',
        'ministry',
        'use',
        'gindi',
        'education'
      ],
      score: 20
    },
    {
      id: 4,
      mname: 'model_name',
      kw: [
        'awareness',
        'young',
        'adolescent',
        'adult',
        'prevalence',
        'cidarette',
        'person',
        'teenage',
        'future',
        'younger',
        'teen',
        'participation',
        'teenager',
        'disadvantaged',
        'schoenborn',
        'initiation',
        'ministry',
        'use',
        'gindi',
        'education'
      ],
      score: 20
    },
    {
      id: 5,
      mname: 'model_name',
      kw: [
        'awareness',
        'young',
        'adolescent',
        'adult',
        'prevalence',
        'cidarette',
        'person',
        'teenage',
        'future',
        'younger',
        'teen',
        'participation',
        'teenager',
        'disadvantaged',
        'schoenborn',
        'initiation',
        'ministry',
        'use',
        'gindi',
        'education'
      ],
      score: 20
    }
  ]
};

export default dummy;
